[package]
name = "nexus"
version = "0.1.0"
authors = ["Yorick Laupa <yorick.laupa@eventstore.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    ".",
    "lib/shared",
    "lib/file-source",
    "lib/tracing-limit",
#    "lib/vector-wasm",
#    "lib/k8s-test-framework",
#    "lib/k8s-e2e-tests",
#    "lib/prometheus-parser",
#    "lib/vector-api-client",
    "lib/remap-lang",
#    "lib/remap-cli",
    "lib/remap-functions",
]

[dependencies]
tracing = "0.1.15"
tracing-core = "0.1.17"
tracing-log = "0.1.0"
tracing-subscriber = "0.2.15"
tracing-futures = { version = "0.2", features = ["futures-01", "futures-03"]}
tracing-tower = { git = "https://github.com/tokio-rs/tracing", rev = "f470db1b0354b368f62f9ee4d763595d16373231" }

async-trait = "0.1"
futures01 = { package = "futures", version = "0.1.25" }
futures = { version = "0.3", default-features = false, features = ["compat", "io-compat"] }
snafu = { version = "0.6.10", features = ["futures-01", "futures"] }
inventory = "0.1.10"

pin-project = "1.0.1"

# Prost
prost = "0.6.1"
prost-types = "0.6.1"

# Serde
serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.33", features = ["raw_value"] }
serde_yaml = "0.8.13"

rlua = { git = "https://github.com/kyren/rlua", rev = "25bd7e6bffef9597466a98bfca80a3056c9e6320" }
indexmap = {version = "1.5.1", features = ["serde-1"]}
regex = "1.3.9"

tokio = { version = "0.2.13", features = ["blocking", "fs", "io-std", "macros", "process", "rt-core", "rt-threaded", "uds", "udp", "signal", "sync", "time", "stream"] }
#tokio-openssl = "0.4.0"
tokio-util = { version = "0.3.1", features = ["codec", "udp"] }

# Metrics
metrics = "0.13.0-alpha.13"
metrics-util = "0.4.0-alpha.10"
metrics-tracing-context = "0.1.0-alpha.7"

logfmt = { version = "0.0.2" }
notify = "4.0.14"
pest = "2.1.3"
pest_derive = "2.1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
bytes = { version = "0.5.6", features = ["serde"] }
stream-cancel = "0.6.2"

http = "0.2"
typetag = "0.1.6"
toml = "0.5.8"

openssl = "0.10.32"
derivative = "2.1.1"
hyper = "0.13"
hyper-openssl = "0.8"
chrono = { version = "0.4.19", features = ["serde"] }
url = "2.2.0"
headers = "0.3"

# Remap Lang
remap = { package = "remap-lang", path = "lib/remap-lang" }
remap-functions = { path = "lib/remap-functions" }

# Tower
tower = { version = "0.3.1", git = "https://github.com/tower-rs/tower", rev = "43168944220ed32dab83cb4f11f7b97abc5818d5", features = ["buffer", "limit", "retry", "timeout", "util"] }

lazy_static = "1.3.0"
glob = "0.3.0"
flate2 = "1.0.19"
once_cell = "1.3"
structopt = "0.3.21"
cidr-utils = "0.5.0"
derive_is_enum_variant = "0.1.1"
exitcode = "1.1.2"
portpicker = "0.1.0"
rand = { version = "0.7.3", features = ["small_rng"] }
rand_distr = "0.3.0"
percent-encoding = "2.1.0"
tokio-openssl = "0.4.0"
colored = "2.0"
getset = "0.1.1"
anyhow = "1.0.37"
dyn-clone = "1.0.3"
hostname = "0.3.1"
base64 = { version = "0.13.0" }
strip-ansi-escapes = "0.1"
bytesize = "1.0.0"
listenfd = "0.3.3"
warp = { version = "0.2.5", default-features = false }
syslog = "5"
syslog_loose = "0.7.0"
heim = { version = "0.1.0-rc.1", features = ["full"] }
snap = "1.0.3"
rdkafka = { version = "0.24.0", features = ["libz", "ssl", "zstd"] }
nats = { version = "0.8.6" }
lru = "0.6.3"

# Aws
rusoto_core = { version = "0.45.0", features = ["encoding"] }
rusoto_es = { version = "0.45.0" }
rusoto_s3 = { version = "0.45.0" }
rusoto_logs = { version = "0.45.0" }
rusoto_cloudwatch = { version = "0.45.0" }
rusoto_kinesis = { version = "0.45.0" }
rusoto_credential = { version = "0.45.0" }
rusoto_firehose = { version = "0.45.0" }
rusoto_sts = { version = "0.45.0" }
rusoto_signature = { version = "0.45.0" }
rusoto_sqs = { version = "0.45.0" }

# GCP
goauth = { version = "0.8.1" }
gouth = { version = "0.1" }
smpl_jwt = { version = "0.5.0" }

async-compression = { version = "0.3.7", features = ["tokio-02", "gzip", "zstd"] }
grok = "~1.0.1"
async-stream = "0.3.0"
bloom = "0.3.2"
evmap = { version = "10.0.2", features = ["bytes"] }
maxminddb = { version = "0.17.0" }
libxid = { git = "https://github.com/EventStore/libxid.git", branch = "enhance-platform-id" }
seahash = { version = "4.0.1" }
itertools = { version = "0.9.0", optional = true }
#vector-api-client = { path = "lib/vector-api-client", optional = true }
num-format = { version = "0.4.0", optional = true }
number_prefix = { version = "0.4", optional = true }
jemallocator = { version = "0.3.0", optional = true }

# Internal
shared = { path = "lib/shared" }
codec = { path = "lib/codec" }
tracing-limit = { path = "lib/tracing-limit" }
file-source = { path = "lib/file-source" }


[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.0"

[target.'cfg(unix)'.dependencies]
atty = "0.2"
nix = "0.19.0"

[build-dependencies]
prost-build = "0.6.1"
tonic-build = { version = "0.3", features = ["prost"] }
built = { version = "0.4.4", features = ["git2", "chrono"] }

[dev-dependencies]
base64 = "0.13"
approx = "0.3.0"
criterion = "0.3"
tempfile = "3.0.6"
libc = "0.2.80"
libz-sys = "1.1.2"
walkdir = "2.2.7"
matches = "0.1.8"
pretty_assertions = "0.6.1"
tokio01-test = "0.1.1"
tower-test = "0.3.0"
tokio-test = "0.2"
tokio = { version = "0.2", features = ["test-util"] }
assert_cmd = "1.0.2"
reqwest = { version = "0.10.9", features = ["json"] }
rusty-fork = "0.3.0"

[features]
default = ["api", "api-client", "sources", "transforms", "sinks", "vendor-all", "unix"]
default-cmake = ["api", "api-client", "sources", "transforms", "sinks", "vendor-all", "unix"]
# Enables features that work only on systems providing `cfg(unix)`
unix = ["jemallocator"]
# These are **very** useful on Cross compilations!
vendor-all = ["vendor-sasl", "vendor-openssl", "vendor-libz"]
vendor-sasl = []
vendor-openssl = ["openssl/vendored"]
vendor-libz = ["libz-sys/static"]

api = [
#    "async-graphql",
#    "async-graphql-warp",
    "itertools"
]

# API client
api-client = [
#    "vector-api-client",
    "num-format",
    "number_prefix",
#    "crossterm",
#    "tui",
]

sources = []
sinks = []
transforms = []
cloud = []

# Target specific release features.
# The `make` tasks will select this according to the appropriate triple.
# Use this section to turn off or on specific features for specific triples.
target-x86_64-unknown-linux-gnu = ["api", "api-client", "sources", "transforms", "sinks", "vendor-all", "unix"]
#default = []

[patch.'https://github.com/tower-rs/tower']
tower-layer = "0.3.1"

[patch.crates-io]
# TODO: update to next 0.12.x (after 0.12.0, if any)
#avro-rs = { version = "0.12.0", git = "https://github.com/flavray/avro-rs", rev = "f28acbbb9860bd62cb24ead83878d7526d075454", optional = true }
# Not maintained, our branch update `sync` and `quote` crates: https://github.com/fitzgen/derive_is_enum_variant/pull/3
derive_is_enum_variant = { version = "0.1.1", git = "https://github.com/timberio/derive_is_enum_variant", rev = "e4550f8ca1366823b8366f0126a7d00ee8ffb080" }
# TODO: update to the next 0.13.x (after 0.13.9, if any) or 0.14 (or higher)
hyper = { version = "0.13", git = "https://github.com/hyperium/hyper", rev = "a00cc20afc597cb55cbc62c70b0b25b46c82a0a6" }
# Not maintained, our branch update `rand` crate: https://github.com/Dentosal/portpicker-rs/pull/3
portpicker = { version = "0.1.0", git = "https://github.com/timberio/portpicker-rs", rev = "d15829e906516720881584ff3301a0dd04218fbb" }
