[package]
name = "nexus"
version = "0.1.0"
authors = ["Yorick Laupa <yorick.laupa@eventstore.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [features]
#default = ["libz-sys/static"]
# default = []

[dependencies]
vector = { path = "./vector", default-features = false, features = [ "sources", "sinks", "transforms", "unix"] }

async-trait = "0.1.48"
bytes = { version = "1.0.0", features = ["serde"] }
chrono = { version = "0.4.19", features = ["serde"] }
eventstore = "1.0.0"
futures = "0.3.13"
inventory = "0.1.10"
lazy_static = "1.3.0"
libxid = { git = "https://github.com/EventStore/libxid.git", branch = "enhance-platform-id" }
prost = "0.7.0"
prost-types = "0.7.0"
regex = "1.4.5"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.64", features = ["raw_value"] }
snafu = { version = "0.6.10", features = ["futures", "futures-01"] }
structopt = "0.3.21"
tokio = { version = "1.4.0", features = ["full"] }
toml = "0.5.8"
typetag = "0.1.6"
tracing = "0.1.25"
http = "0.2"
rustls = { version = "0.19", features = ["dangerous_configuration"] }
webpki = "0.21"
metrics = { version = "0.14", default-features = false }
tokio-stream = { version = "0.1.5", default-features = false, features = ["net", "sync"] }
hyper = { version = "0.14", default-features = false, features = ["stream"] }
hyper-openssl = { version = "0.9.1", default-features = false, features = ["tcp"] }

[lib]
name = "nexus"
path = "src/lib.rs"

[[bin]]
name = "nexus"
path = "src/cli/nexus.rs"
