[package]
name = "nexus"
version = "0.1.0"
authors = ["Yorick Laupa <yorick.laupa@eventstore.com>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.15"
tracing-core = "0.1.17"
tracing-log = "0.1.0"

async-trait = "0.1"
futures01 = { package = "futures", version = "0.1.25" }
futures = { version = "0.3", default-features = false, features = ["compat", "io-compat"] }
snafu = { version = "0.6.10", features = ["futures-01", "futures"] }
inventory = "0.1.10"
tracing-futures = { version = "0.2", features = ["futures-01", "futures-03"]}

pin-project = "1.0.1"

# Prost
prost = "0.6.1"
prost-types = "0.6.1"

# Serde
serde = { version = "1.0.117", features = ["derive"] }
serde_json = { version = "1.0.33", features = ["raw_value"] }
serde_yaml = "0.8.13"

rlua = { git = "https://github.com/kyren/rlua", rev = "25bd7e6bffef9597466a98bfca80a3056c9e6320", optional = true }
indexmap = {version = "1.5.1", features = ["serde-1"]}
regex = "1.3.9"

tokio = { version = "0.2.13", features = ["blocking", "fs", "io-std", "macros", "process", "rt-core", "rt-threaded", "uds", "udp", "signal", "sync", "time", "stream"] }
#tokio-openssl = "0.4.0"
tokio-util = { version = "0.3.1", features = ["codec"] }

# Metrics
metrics = "0.13.0-alpha.13"
metrics-util = "0.4.0-alpha.10"
metrics-tracing-context = "0.1.0-alpha.7"

logfmt = { version = "0.0.2", optional = true }
notify = "4.0.14"
pest = "2.1.3"
pest_derive = "2.1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
bytes = { version = "0.5.6", features = ["serde"] }
stream-cancel = "0.6.2"

http = "0.2"
typetag = "0.1.6"
toml = "0.5.8"

[target.'cfg(unix)'.dependencies]
nix = "0.19.0"

[build-dependencies]
prost-build = "0.6.1"
tonic-build = { version = "0.3", features = ["prost"] }
built = { version = "0.4.4", features = ["git2", "chrono"] }

[features]
default = []
