name: CI
on: 
    pull_request:
    push:
      branches:
        - master

jobs:
  backend:
    name: tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cache Rust stuff
        uses: actions/cache@v2
        env:
          cache-name: cache-target-dir
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}

      - name: Install Rust
        run: |
          rustup default stable
          cargo install just
          cargo install taplo-cli

      - name: Build
        run: just build

      - name: Test
        run: just test
